### ISSUE TITLE
Split thermal pads

### ISSUE THREAD

**Issue by robertfoss** [KiCad/Housings_DFN_QFN.pretty#14]
Are the thermal pads meant to be split into multiple sub-pads?
Or could I submit a fix for this?

**Comment by poeschlr** [comment]
A bit late but yes this is to get better results when reflow soldering these parts. (As long as the paste layer is split up of course. Otherwise it might just be a mistake by the original author of the footprint. As far as i can tell most exposed pads have indeed separate pads to split up the paste layer.)

Quote from http://www.nxp.com/docs/en/application-note/AN1902.pdf1:
> The segmented PCB design facilitates the solder paste flux outgassing during reflow, thereby promoting a lower voiding level of the completed solder joint. At the same time, the maximum size of a single solder void is limited by the dimensions of a single matrix segment.

**Comment by SchrodingersGat** [comment]
@robertfoss yes in many cases this is purposeful, based on the manufacturer datasheet for each package. I'm closing this issue but please feel free to discuss further.
