### ISSUE TITLE
Pad shape varies

### ISSUE THREAD

**Issue by diggit** [KiCad/Housings_DFN_QFN.pretty#24]
`Housings_DFN_QFN:QFN-28-1EP_5x5mm_Pitch0.5mm` has oval pads
`Housings_DFN_QFN:QFN-24-1EP_4x4mm_Pitch0.5mm` has rectangular pads
Probably more, I noticed it here.

IMO there is no reason to have different pad shapes for same type of package.

(I like how OrCAD sources pad shapes externally. Maybe KiCAD will implement it in future library format...)

**Comment by poeschlr** [comment]
Sorry for the late answer.

I would guess that the different footprints where designed by different people.
Using different guidelines. (One manufacturer might suggest rectangular pads while another manufacturer might suggest rounded pads.)
I can't really find out which guideline has been used for the two footprints you mentioned because they to not link to a datasheet or another type of specification.

We would certainly welcome a volunteer to rework this lib such that it has better consistency. (And better compliance with the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention))

Other things that might not be done correctly for some or all of the footprints: 
- ${KISYS3DMOD} missing from 3d model path, 
- wrong fab line width
- wrong silk line width
- inconsistent exposed pad split up
- missing datsheet link, documentation, missing or wrong keywords
- ...

**Comment by suzizecat** [comment]
I'm adding something to this issue : i just found out that there is some QFN FP which can have different specifications. In example, the `Housings_DFN_QFN:QFN-28-1EP_6x6mm_Pitch0.65mm`

This one gives in reference a PDF which i believe is from Microchip :  http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf (page 289)

I used it on a design but i just found out that this don't meet the specifications of my component, the SX1272 as you may see in the datasheet : http://www.semtech.com/images/datasheet/sx1272.pdf (page 126)

I even think that it may be a risk to make shorts between the pins of the component and the EP of the FP...

What should i do with that ? (or if i got to, how should i name the new footprint used by semtech ?)

**Comment by poeschlr** [comment]
Wow that's bad. The semtec version has much smaller pins then the microchip version. (The ep makes it even worse.)

Should we append the ep size and maybe even the center distance between the pads?
(or should we mark them as manufacturer specific?)

**Comment by suzizecat** [comment]
I just saw that even microchip have different variant for the QFN28 depending on the contact lenght between the chip and the PCB (0.55mm and 0.4mm) in 6x6mm version. (page 189 for the 0.55mm and page 191 for the 0.4 one)

It looks like my version would be the 0.4mm one with extended pad (outside the component body), maybe to help to solder ?

BTW, why there is something like 16 pad just for the EP in the current FP ?

**Comment by evanshultz** [comment]
Since this falls into the general category of "pad shape varies", even though it's off the original topic, I'll add a story of the same problem I ran into several months ago.

[ISL8014A](http://www.intersil.com/content/dam/Intersil/documents/isl8/isl8014a.pdf) and [THAT1583](http://www.thatcorp.com/datashts/THAT_1583_Datasheet.pdf) have incompatible 4x4mm 16-pin QFN packages. While they're similar, the thermal pads are 2.1mm or 2.6mm square. Depending on the footprint design, solder could become trapped under the part and create shorts. Or it might even be possible, again depending on the footprint design, for the bigger thermal pad to touch the pads on a footprint intended for the smaller thermal pad. Either way is bad.

So with that consideration, I agree that the thermal pad size should be specified in the footprint name and this requirement added to KLC. Perhaps something like `QFN-16-1EP-2.1x2.1mm_4x4mm_Pitch0.65mm`, adding the pad size just after "1EP"?

**Comment by poeschlr** [comment]
Currently ep is at the end and i would suggest this should not change. In the meantime i think the better option is to include the pin length instead of the ep size. This would also work for packages without ep.

**Comment by SchrodingersGat** [comment]
1. Specifying the endpoint dimensions is probably a good idea, although the names are now getting pretty long.
1. The best idea is to add the exact footprint according to the manufacturer specs. It's better to have many specific footprints rather than try to have a one-size-fits-many approach.

When adding a footprint using manufacturer specs, use the `Manufacturer_PkgName` format e.g. `Microchip-ML_QFN-28`

**Comment by suzizecat** [comment]
@SchrodingersGat : But since almost all the footprints come from a manufacturer DS (or i believe so), which one should be the "standard" one ? Should we add manufacturer on all footprints ? (i don't think so since lot of footprint are generic, but you got my point)

**Comment by SchrodingersGat** [comment]
"Standard" doesn't make sense here - QFN parts are especially bad as every manufacturer has their own variant.

If a footprint is usable for multiple manufacturer applications, it should be named based on the dimension convention. If there are multiple EP shapes, they should be included in the name.

If however a footprint is specific to an individual manufacturer, it should be named according to their specification.

**Comment by evanshultz** [comment]
Pages 31-34 of https://www.cskl.de/fileadmin/downloads/PCBLIBRARIES/Documentation/What-is-New-in-IPC-7351C_.pdf talk about this topic, and recommend using the manufacturer prefix for just this purpose. Not sure if you already read this, Oliver, but IPC is saying the same thing.

**Comment by SchrodingersGat** [comment]
@evanshultz yes it was based on this that the naming convention for KLC was updated (to include manufacturer prefix).

I am strongly in favour of adding the manufacturer name - it is vital especially for small pitch components that the dimensions are exact.

**Comment by SchrodingersGat** [comment]
@diggit 



In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)
